<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'OCA\\Sharing\\AppInfo\\Application' => $baseDir . '/../lib/AppInfo/Application.php',
    'OCA\\Sharing\\Capabilities' => $baseDir . '/../lib/Capabilities.php',
    'OCA\\Sharing\\Controller\\ApiController' => $baseDir . '/../lib/Controller/ApiController.php',
    'OCA\\Sharing\\Exception\\ShareCreationNotAllowedException' => $baseDir . '/../lib/Exception/ShareCreationNotAllowedException.php',
    'OCA\\Sharing\\Exception\\ShareDeletionNotAllowedException' => $baseDir . '/../lib/Exception/ShareDeletionNotAllowedException.php',
    'OCA\\Sharing\\Exception\\ShareException' => $baseDir . '/../lib/Exception/ShareException.php',
    'OCA\\Sharing\\Exception\\ShareInvalidException' => $baseDir . '/../lib/Exception/ShareInvalidException.php',
    'OCA\\Sharing\\Exception\\ShareInvalidRecipientSearchParametersException' => $baseDir . '/../lib/Exception/ShareInvalidRecipientSearchParametersException.php',
    'OCA\\Sharing\\Exception\\ShareNotFoundException' => $baseDir . '/../lib/Exception/ShareNotFoundException.php',
    'OCA\\Sharing\\Exception\\ShareUpdateNotAllowedException' => $baseDir . '/../lib/Exception/ShareUpdateNotAllowedException.php',
    'OCA\\Sharing\\Features\\ExpirationShareFeature' => $baseDir . '/../lib/Features/ExpirationShareFeature.php',
    'OCA\\Sharing\\Manager' => $baseDir . '/../lib/Manager.php',
    'OCA\\Sharing\\Migration\\Version1000Date20250929161325' => $baseDir . '/../lib/Migration/Version1000Date20250929161325.php',
    'OCA\\Sharing\\Model\\AShareFeature' => $baseDir . '/../lib/Model/AShareFeature.php',
    'OCA\\Sharing\\Model\\AShareRecipientType' => $baseDir . '/../lib/Model/AShareRecipientType.php',
    'OCA\\Sharing\\Model\\AShareSourceType' => $baseDir . '/../lib/Model/AShareSourceType.php',
    'OCA\\Sharing\\Model\\Share' => $baseDir . '/../lib/Model/Share.php',
    'OCA\\Sharing\\Model\\ShareProperty' => $baseDir . '/../lib/Model/ShareProperty.php',
    'OCA\\Sharing\\RecipientTypes\\GroupShareRecipientType' => $baseDir . '/../lib/RecipientTypes/GroupShareRecipientType.php',
    'OCA\\Sharing\\RecipientTypes\\UserShareRecipientType' => $baseDir . '/../lib/RecipientTypes/UserShareRecipientType.php',
    'OCA\\Sharing\\Registry' => $baseDir . '/../lib/Registry.php',
    'OCA\\Sharing\\ResponseDefinitions' => $baseDir . '/../lib/ResponseDefinitions.php',
    'OCA\\Sharing\\SourceTypes\\NodeShareSourceType' => $baseDir . '/../lib/SourceTypes/NodeShareSourceType.php',
);
